language: python

services:
  - docker

before_install:
  - docker pull jramapuram/fid-tensorflow:1.14.0-py3

script:
  # - travis_wait 3000 sleep infinity & sh ./docker/run_cpu.sh "python test_sync.py"
  - travis_wait 240 sh ./docker/run_cpu.sh "python test_sync.py"
